# Generated by Django 3.2.16 on 2024-10-31 07:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NhanVien',
            fields=[
                ('ma_nhan_vien', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('ho_ten', models.CharField(max_length=100)),
                ('don_vi', models.CharField(max_length=100)),
                ('vai_tro', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='TrangBi',
            fields=[
                ('ma_trang_bi', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('ten', models.CharField(max_length=100)),
                ('tinh_trang', models.CharField(max_length=50)),
                ('loai', models.CharField(choices=[('PC', 'PC'), ('Laptop', 'Laptop'), ('ThietBiMang', 'Thiết bị mạng')], max_length=20)),
                ('nguoi_quan_ly', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quan_ly_trang_bi', to='home.nhanvien')),
            ],
        ),
        migrations.CreateModel(
            name='SuaChua',
            fields=[
                ('ma_sua_chua', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('ngay', models.DateField()),
                ('noi_dung', models.TextField()),
                ('ma_trang_bi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.trangbi')),
                ('nguoi_sua', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sua_chua', to='home.nhanvien')),
            ],
        ),
        migrations.CreateModel(
            name='BanGiao',
            fields=[
                ('ma_ban_giao', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('ngay', models.DateField()),
                ('ben_giao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ban_giao', to='home.nhanvien')),
                ('ben_nhan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nhan_giao', to='home.nhanvien')),
                ('ma_trang_bi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.trangbi')),
            ],
        ),
    ]
